[package]
name = "althread-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
althread = { workspace = true }
fastrand = { workspace = true }
owo-colors = "4.1.0"

[lints]
workspace = true
