[package]
name = "althread-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.11", features = ["cargo", "derive", "error-context"] }
lazy_static = "1.5.0"
pest = "2.7.10"
pest_derive = "2.7.10"
rand = "0.8.5"
