name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your primary branch
  workflow_dispatch:  # Allow manual runs

jobs:
  build-rust:
    name: Build Rust Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build Rust Project
        run: |
          cargo build --verbose --release

      - name: Build Web Assembly (Wasm)
        run: |
          cd web
          cargo install wasm-pack
          wasm-pack build --target web --release

      - name: Upload Wasm Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wasm-artifacts
          path: web/pkg

  build-web:
    name: Build Web Editor
    runs-on: ubuntu-latest
    needs: build-rust

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Wasm Artifacts
        uses: actions/download-artifact@v3
        with:
          name: wasm-artifacts

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install Dependencies
        run: |
          corepack enable
          corepack prepare pnpm@latest-9 --activate
          pnpm install --store-dir .pnpm-store

      - name: Build Web Editor
        run: |
          cd web
          pnpm build --public-url ./editor
          mv dist ../editor

      - name: Upload Built Web Editor
        uses: actions/upload-artifact@v3
        with:
          name: web-editor
          path: editor


  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build-web
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Built Web Editor
        uses: actions/download-artifact@v3
        with:
          name: web-editor

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm --prefix ./doc install

      - name: Build site
        run: pnpm --prefix ./doc run build
  
      - name: Deploy to althread.github.io 
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          # Start SSH agent and add the deploy key
          eval "$(ssh-agent -s)"
          ssh-add <(echo "${{ secrets.DEPLOY_KEY }}")

          # Clone the target repository (orgname.github.io)
          git clone --branch=gh-pages git@github.com:althread/althread.github.io.git deploy

          # Remove old files and copy new ones
          rm -rf deploy/*
          cp -r doc/build deploy/docs 
          cp -r editor deploy/editor
          cp doc/index.html deploy/ # The landing page
          
          # Commit and push changes
          cd deploy
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy site"
          git push origin gh-pages

